//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class story
    {
        public story()
        {
            this.images = new HashSet<image>();
        }
    
        public decimal id { get; set; }
        public decimal userid { get; set; }
        public string description { get; set; }
        public string story1 { get; set; }
    
        public virtual ICollection<image> images { get; set; }
        public virtual user user { get; set; }
    }
}
