//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class story
    {
        public int idstory { get; set; }
        public int user_Id { get; set; }
        [Display(Name = "Description")]
        public string description { get; set; }
        [Display(Name = "Story")]
        public string text { get; set; }
        [Display(Name = "Picture")]
        public string image1 { get; set; }
    
        public virtual user user { get; set; }
    }
}
