//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.image = new HashSet<image>();
            this.story = new HashSet<story>();
        }
    
        public decimal studentid { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string country { get; set; }
        public string password { get; set; }
        public byte[] avatar { get; set; }
        public string homeu { get; set; }
        public string course { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
    
        public virtual ICollection<image> image { get; set; }
        public virtual ICollection<story> story { get; set; }
    }
}
