//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.stories = new HashSet<story>();
        }
    
        public int Id { get; set; }
        public int studentId { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Country { get; set; }
        public string HomeU { get; set; }
        public System.DateTime Dob { get; set; }
        public string Course { get; set; }
        public byte[] Avatar { get; set; }
    
        public virtual ICollection<story> stories { get; set; }
    }
}
